notifications:
  email: false
dist: trusty
sudo: false
cache:
  directories:
  - $HOME/.cache/pip

language: python

matrix:
  include:
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.6-dev"
    env: TOXENV=py36
  - python: "3.7-dev"
    env: TOXENV=py37
  # Meta
  - python: "3.6"
    env: TOXENV=codestyle

install:
- pip install tox

before_script:
- docker-compose up -d
- sleep 5

script:
- tox

after_success:
- tox -e coverage-report
