language: python
python:
- "3.6"
- "3.6-dev"
- "3.7-dev"
- "nightly"
cache: pip

install:
- pip install -r requirements/test.txt
- pip install -e .

script:
- pytest -l --cov=amqproto --cov-report=term-missing:skip-covered --cov-config=tests/unit/coveragerc tests/unit
- pytest -l --cov=amqproto --cov-report=term-missing:skip-covered --cov-config=tests/functional/coveragerc tests/functional -s

services:
- rabbitmq  # required by functional tests
